"""Generate src/candle/_generated/view_funcs.py — the inventory of view ops.

Sub-batch 1A: emit data-only inventory.  Sub-batch 1B will plug per-op
forward/reverse callables.
"""
from __future__ import annotations


# Mirrors PyTorch tools/autograd/gen_inplace_or_view_type.py::VIEW_FUNCTIONS
# restricted to ops candle currently implements as views.  Sub-batch 1B
# extends this with per-op view_func / rev_view_func bodies.
VIEW_OPS = (
    "view",
    "reshape",
    "permute",
    "transpose",
    "squeeze",
    "unsqueeze",
    "expand",
    "narrow",
    "select",
    "slice",
    "as_strided",
    "flatten",
    "t",
    "unfold",
    "view_as_real",
    "view_as_complex",
    "contiguous",
    "movedim",
    "unflatten",
)


_HEADER = '''\
"""Auto-generated view-op inventory — DO NOT EDIT.

Generated by tools/autograd/gen_view_funcs.py.
Sub-batch 1A populates the static inventory; 1B fills in the per-op
view_func / rev_view_func bodies.
"""
from __future__ import annotations

'''


def gen_view_funcs() -> str:
    """Return the source text of src/candle/_generated/view_funcs.py."""
    parts = [_HEADER]
    parts.append("VIEW_OPS = (\n")
    for op in VIEW_OPS:
        parts.append(f"    {op!r},\n")
    parts.append(")\n")
    return "".join(parts)
