"""Generate registration code that wires generated wrappers into the dispatcher."""
from __future__ import annotations

from .model import DifferentiabilityInfo


_MULTI_OUTPUT_RUNTIME_OPS = {
    "split",
    "unsafe_split",
    "split_with_sizes",
    "unsafe_split_with_sizes",
    "unbind",
}


def gen_registration(infos: list[DifferentiabilityInfo]) -> str:
    """Generate registration.py source."""
    parts = [_HEADER]
    parts.append("\n\ndef register_generated_autograd_kernels():")
    parts.append("    from .._dispatch.registration import register_autograd_kernels, register_autograd_post_kernels")
    parts.append("    from .._dispatch.registry import registry")
    parts.append("    from . import variable_type as _VT_PY")
    parts.append("    try:")
    parts.append("        from . import _variable_type_cy as _VT_CY")
    parts.append("    except ImportError:")
    parts.append("        _VT_CY = None")
    parts.append("    _VT = _VT_CY if _VT_CY is not None else _VT_PY\n")
    seen_ops = set()
    for info in infos:
        op = info.op_name
        if op in seen_ops:
            continue
        seen_ops.add(op)
        if op in _MULTI_OUTPUT_RUNTIME_OPS:
            parts.append(f"    # {op}: handled by _autograd_multi_output in autograd.py")
            continue
        func_name = f"{op}_autograd"
        post_func_name = f"{op}_autograd_post"
        parts.append(f"    if registry.has({op!r}):")
        parts.append(
            f"        register_autograd_kernels({op!r}, default=_VT.{func_name}, cpu=_VT.{func_name}, cuda=_VT.{func_name}, npu=_VT.{func_name}, meta=_VT.{func_name})"
        )
        parts.append(f"        register_autograd_post_kernels({op!r}, _VT.{post_func_name})")
    parts.append("")
    parts.append("    # Legacy ops (not in derivatives.yaml)")
    parts.append("    from .variable_type_legacy import register_legacy_autograd_kernels")
    parts.append("    register_legacy_autograd_kernels()")
    parts.append("")
    return "\n".join(parts)


_HEADER = '''\
"""Auto-generated autograd kernel registration — DO NOT EDIT.

Generated by tools/autograd/gen_registration.py from derivatives.yaml.
"""
# pylint: disable=too-many-statements,too-many-branches
'''
