"""Generate forward autograd wrappers from DifferentiabilityInfo."""
from __future__ import annotations

from .model import DifferentiabilityInfo
from .gen_functions import _safe_param


def gen_variable_type(infos: list[DifferentiabilityInfo]) -> str:
    """Generate the full variable_type.py source."""
    parts = [_HEADER]
    for info in infos:
        parts.append(_gen_one_wrapper(info))
    return "\n".join(parts) + "\n"


_HEADER = '''\
"""Auto-generated forward autograd wrappers — DO NOT EDIT.

Generated by tools/autograd/gen_variable_type.py from derivatives.yaml.
"""
from __future__ import annotations

from ..autograd.grad_mode import GradMode
from ..autograd.anomaly_mode import annotate_node_creation
from .._backends.autograd import _strip_autograd_keys
from .._dispatch.dispatcher import current_dispatch_keyset, redispatch
from . import functions as _F
'''


def _gen_one_wrapper(info: DifferentiabilityInfo) -> str:
    cls_name = info.backward_name
    op_name = info.op_name
    func_name = f"{op_name}_autograd"

    tensor_args = info.tensor_args
    non_tensor_args = info.non_tensor_args
    saved_inputs = info.all_saved_inputs
    saved_outputs = info.all_saved_outputs
    diff_inputs = info.differentiable_inputs

    lines: list[str] = []

    # Build function signature
    params = []
    for arg in info.args:
        if arg.default is not None:
            params.append(f"{arg.name}={arg.default}")
        else:
            params.append(arg.name)
    sig = ", ".join(params)
    lines.append(f"\n\ndef {func_name}({sig}, **_kwargs):")

    # Dispatch setup
    lines.append("    active_keyset = current_dispatch_keyset()")
    lines.append("    raw_keyset = _strip_autograd_keys(active_keyset)")

    # Forward call
    fwd_args = ", ".join([f'"{op_name}"', "raw_keyset"] + [a.name for a in info.args])
    lines.append(f"    result = redispatch({fwd_args}, **_kwargs)")

    # Check requires_grad — Tensor[] needs iteration
    if len(diff_inputs) == 1:
        a = diff_inputs[0]
        if a.is_tensor_list:
            rg_check = f"any(getattr(t, 'requires_grad', False) for t in {a.name})"
        elif a.is_optional_tensor:
            rg_check = f"({a.name} is not None and {a.name}.requires_grad)"
        else:
            rg_check = f"{a.name}.requires_grad"
    elif len(diff_inputs) > 1:
        parts = []
        for a in diff_inputs:
            if a.is_tensor_list:
                parts.append(f"any(getattr(t, 'requires_grad', False) for t in {a.name})")
            elif a.is_optional_tensor:
                parts.append(f"({a.name} is not None and getattr({a.name}, 'requires_grad', False))")
            else:
                parts.append(f"getattr({a.name}, 'requires_grad', False)")
        rg_check = " or ".join(parts)
    else:
        # No differentiable inputs — skip autograd entirely
        lines.append("    return result")
        return "\n".join(lines)

    lines.append(f"    if GradMode.enabled and ({rg_check}):")

    # Build inputs list for Node — Tensor[] needs unpacking
    has_tensor_list = any(a.is_tensor_list for a in diff_inputs)
    if has_tensor_list:
        # Unpack tensor lists into the inputs tuple
        unpack_parts = []
        for a in diff_inputs:
            if a.is_tensor_list:
                unpack_parts.append(f"*{a.name}")
            else:
                unpack_parts.append(a.name)
        inputs_expr = f"({', '.join(unpack_parts)},)"
    elif any(a.is_optional_tensor for a in diff_inputs):
        input_names = [a.name for a in diff_inputs]
        lines.append(f"        _inputs = [x for x in ({', '.join(input_names)},) if x is not None]")
        inputs_expr = "_inputs"
    else:
        input_names = [a.name for a in diff_inputs]
        inputs_expr = f"({', '.join(input_names)},)"

    lines.append(f"        grad_fn = _F.{cls_name}({inputs_expr}, raw_keyset=raw_keyset, active_keyset=active_keyset)")
    lines.append(f"        annotate_node_creation(grad_fn)")

    # Save tensors — skip Tensor[] args (they're accessed via Node.inputs)
    if saved_inputs or saved_outputs:
        save_kw = []
        for name in saved_inputs:
            arg = next((a for a in info.args if a.name == name), None)
            if arg and arg.is_tensor_list:
                continue  # Tensor[] saved via Node.inputs, not _save()
            save_kw.append(f"{_safe_param(name)}={name}")
        for name in saved_outputs:
            # Multi-output: result0 -> result[0], result1 -> result[1], etc.
            if name == "result":
                save_kw.append(f"{_safe_param(name)}=result")
            elif name.startswith("result") and name[6:].isdigit():
                idx = name[6:]
                save_kw.append(f"{_safe_param(name)}=result[{idx}]")
            else:
                save_kw.append(f"{_safe_param(name)}=result")
        if save_kw:
            lines.append(f"        grad_fn._save({', '.join(save_kw)})")

    # Save non-tensor args
    for arg in non_tensor_args:
        lines.append(f"        grad_fn._{arg.name} = {arg.name}")

    # Attach grad_fn
    if info.is_multi_output:
        out_diff = info.output_differentiability
        for i in range(info.num_outputs):
            if out_diff is None or (i < len(out_diff) and out_diff[i]):
                lines.append(f"        result[{i}].grad_fn = grad_fn")
                lines.append(f"        result[{i}].requires_grad = True")
    else:
        lines.append("        result.grad_fn = grad_fn")
        lines.append("        result.requires_grad = True")
    lines.append("    return result")

    return "\n".join(lines)
