"""Auto-generated view-op inventory — DO NOT EDIT.

Generated by tools/autograd/gen_view_funcs.py.
Sub-batch 1A populates the static inventory; 1B fills in the per-op
view_func / rev_view_func bodies.
"""
from __future__ import annotations

VIEW_OPS = (
    'view',
    'reshape',
    'permute',
    'transpose',
    'squeeze',
    'unsqueeze',
    'expand',
    'narrow',
    'select',
    'slice',
    'as_strided',
    'flatten',
    't',
    'unfold',
    'view_as_real',
    'view_as_complex',
    'contiguous',
    'movedim',
    'unflatten',
)
